server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Kafka ? notification-service is ONLY a consumer
# It reads from three topics but never publishes anything
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.smartbanking.common.event
spring.kafka.consumer.properties.spring.json.use.type.headers=true
# earliest = on first startup, read all events from beginning of topic
# This means if notification-service was down, it catches up on restart
spring.kafka.consumer.auto-offset-reset=earliest

# JavaMailSender ? Mailtrap credentials for development
# Sign up free at https://mailtrap.io
# Replace these with your actual Mailtrap SMTP credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=smartbankingplatformservices@gmail.com
spring.mail.password=

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.mail.from=smartbankingplatformservices@gmail.com
notification.mail.from-name=Smart Banking Platform
